### ISSUE TITLE
Failed to load ng-dygraphs.component.html

### ISSUE THREAD

**Issue by areiterer** [mpx200/ng-dygraphs#18]
Since updating from 0.3.5 to 0.3.8/0.3.9 I get some weird errors when I want to start my application: 

`Uncaught ReferenceError: exports is not defined
    at scripts.bundle.js:sourcemap:44808`

`GET http://localhost:4200/ng-dygraphs.component.html 404 (Not Found)`

`Unhandled Promise rejection: Failed to load ng-dygraphs.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load ng-dygraphs.component.html`

When I go back to 0.3.5 everything works fine.

**Comment by JimiC** [comment]
Confirmed. I have the same issue. The issue is created because from `0.3.6` we are pointing to an entry point that is not compatible when used with a `ts` `angular` project.

Everything works if you
- remove `"main": "./lib/index.js",` from `package.json` of `ng-dygraphs` folder in `node_modules`
- remove ` "../node_modules/ng-dygraphs/lib/index.js"` from `scripts` in `.angular-cli.json`
 - add the following in `tsconfig.json` of the `angular` project
```
"include" : [
    "src/**/*",
    "node_modules/ng-dygraphs/index.ts"
  ]
```
Now it will work for a `ts` project.

**Comment by JimiC** [comment]
@areiterer Please try my suggestions and let me know if the workaround works for you.

**Comment by mpx200** [comment]
let's keep this open till we migrate it to `ng-packagr`, until then please try with workaround

**Comment by areiterer** [comment]
Thanks for the workaround, I just tried it and it works for me. 
As soon as the next version is out, my colleague will try it out. Thanks for the good work!

**Comment by mpx200** [comment]
Hi @areiterer  can you please check out version 0.4.0

**Comment by JimiC** [comment]
@areiterer With `0.4.0` you can remove the `include` section in `tsconfig.json`.

**Comment by areiterer** [comment]
Coworker just tried it - everything works fine again! Thanks!
